import type { Metadata } from "next";
import Topbar from "./components/topbar";
import Navbar from "./components/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Legality Panama",
  description: "Generated by Adrien Agency",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          className="banner h-screen bg-cover bg-center"
          style={{ backgroundImage: "url(/images/banner-photo.png)" }}
        >
          <div className=" bg-daintree-950/80 h-screen px-10">
            <div className="container mx-auto">
              <Topbar />
              <Navbar />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
